package com.republicate.kddl.hypersql

import com.republicate.kddl.SQLFormatter

class HyperSQLFormatter(quoted: Boolean, uppercase: Boolean): SQLFormatter(quoted, uppercase) {

    override fun mapType(type: String): String? {
        return when (type) {
            "serial" -> "integer generated by default as identity"
            // "bigserial" TODO
            else -> super.mapType(type)
        }
    }

}
