package com.republicate.kddl.hypersql

import com.republicate.kddl.SQLFormatter

class HyperSQLFormatter(quoted: Boolean, uppercase: Boolean, idempotent: Boolean = false): SQLFormatter(quoted, uppercase, idempotent) {

    override val supportsEnums = true

    // HSQLDB has no native ENUM: model it as a CHECKed varchar domain, the portable analog of PG's enum type.
    // Not idempotent-guarded (HSQLDB lacks CREATE DOMAIN IF NOT EXISTS); the create script drops the schema first.
    override fun defineEnum(typeName: String, values: List<String>): String {
        val qTypeName = transform(typeName)
        val width = values.maxOf { it.length }
        val inList = values.joinToString(", ") { "'$it'" }
        return "CREATE DOMAIN $qTypeName AS VARCHAR($width) CHECK (VALUE IN ($inList));"
    }

    override fun mapType(type: String): String? {
        return when (type) {
            "serial" -> "integer generated by default as identity"
            // "bigserial" TODO
            else -> super.mapType(type)
        }
    }

}
